Updates of scons builds of viper armel
Had to add "first_mach" checks in linux module
SConscripts, when they are called for multiple machine types, so
that it doesn't try to install headers twice, resulting in this error:

    AssertionError: Installing source ['build_arm/linux/arinc_titan/arinc.h',
        'build_arm/linux/arinc_viper/arinc.h'] into target
        ['/opt/nidas/arm/include/nidas/linux/arinc/arinc.h']: target and
    source lists must have same length.