Now filters pg_dump results for just the INSERT statements; this will reduce the SQL error messages to be just:
   ERROR:  duplicate key violates unique constraint "calibrations_cal_date_key"

These ERRORs are to be expected since the INSERTs are just re-merging
pre-existing rows. 

<site>_rid now replaced with an auto-incrementing SQL statement;
this should ensure that newer cloned row's rid's are not reused.

Now mitigates the GV's newer pg_dump.  The newer version does
not use the '-d' when specifing the database name.