Add sensor class for pms2d house keeping.  Not totally finished.  Does shadow or correctly, but I need to visit with Spowart on codes for the rest.
Also apps aren't building because of this;
build_x86/build_dynld/libnidas_dynld.so: undefined reference to `vtable for nidas::dynld::raf::TwoD_House'